services:
  mysql:
    image: mysql:8.4
    container_name: mysql-invoices
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoices_db
      MYSQL_USER: invoices_user
      MYSQL_PASSWORD: invoices_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_invoices_data:/var/lib/mysql

volumes:
  mysql_invoices_data:
