services:
  mysql:
    image: mysql:8.4
    container_name: mysql-orders
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
      MYSQL_USER: orders_user
      MYSQL_PASSWORD: orders_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_orders_data:/var/lib/mysql

volumes:
  mysql_orders_data:
